const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const read = relative => fs.readFileSync(path.join(root, relative), 'utf8');

const html = read('src/renderer/index.html');
const popup = read('src/renderer/popup.js');
const core = read('src/renderer/scripts/popup/00-core.js');
const commodity = read('src/renderer/scripts/popup/11-commodities.js');
const css = read('src/renderer/styles/15-commodities.css');
const styles = read('src/renderer/styles.css');
const service = read('src/main/dhan-data-service.js');
const chartWorkspacePart = read('src/renderer/scripts/popup/parts/chart-workspace/02-model-and-order-context.jsfrag');
const chartSurfacePart = read('src/renderer/scripts/popup/parts/chart-workspace/04-surface-events.jsfrag');
const chartIndicators = read('src/renderer/scripts/shared/chart-indicators.js');
const chartEngine = read('src/renderer/scripts/popup/chart-engine.js');

assert(html.includes('data-tab="commodities"') && html.includes('id="pane-commodities"'));
assert(popup.includes("commodities: 'scripts/popup/11-commodities.js'"));
assert(popup.includes("safeTab === 'commodities'") && popup.includes('ensureCommoditiesLoaded'));
assert(core.includes("'commodities'") && core.includes('globalThis.renderCommodities?.(preloaded)'));
assert(styles.includes("styles/15-commodities.css"));
assert(commodity.includes("marketData('commodity_snapshot'") && commodity.includes("marketData('live_feed_subscribe'"));
assert(commodity.includes("marketData('commodity_margin_preview'") && commodity.includes('Estimate Margin'));
assert(commodity.includes('Save Paper Plan') && commodity.includes('Open Broker Terminal'));
assert(commodity.includes('fwdCommodityPlans.v1') && commodity.includes('writePlans'));
assert(commodity.includes('Calendar spread view compares two MCX futures expiries.'));
assert(commodity.includes("marketData('commodity_spread_history'") && commodity.includes('Spread P&amp;L Chart'));
assert(commodity.includes('GOLD / GOLDM matched') && commodity.includes('1 GOLD lot versus 10 GOLDM lots'));
assert(commodity.includes('Close / roll before') && commodity.includes('A narrower calendar spread may profit'));
assert(commodity.includes('lastCompletedMarketDate') && commodity.includes("addEventListener('input'"));
assert(commodity.includes('Dhan daily close data for today is usually available only after the session closes'));
assert(commodity.includes("marketData('commodity_analysis'") && commodity.includes('Commodity Lab'));
assert(commodity.includes("marketData('commodity_spread_scanner'") && commodity.includes('Spread Desk'));
assert(commodity.includes('commodityStopSpreadScan') && commodity.includes('commodityForceSpreadScan') && commodity.includes('stopSpreadScan'));
assert(commodity.includes('spreadDeskRunId') && commodity.includes('Late API results from the stopped request will be ignored.'));
assert(commodity.includes("{ ...payload, type: 'dhan_data', action }") && commodity.includes('spreadType: state.spreadDeskType'));
assert(!commodity.includes("marketData('commodity_spread_scanner', { type: state.spreadDeskType"));
assert(commodity.includes("marketData('commodity_spread_quotes'") && commodity.includes('refreshSpreadQuotes'));
assert(commodity.includes('Open Daily Decision Chart') && commodity.includes('Open Synchronized 1H') && commodity.includes('Save Spread Watch'));
assert(commodity.includes('data-commodity-calendar-chart=') && commodity.includes('Spread Chart'));
assert(commodity.includes('Calendar Spread 1D') && commodity.includes('Leg Chart'));
assert(commodity.includes('function commoditySnapshotSpreadRow') && commodity.includes('function openCommodityCalendarChart'));
assert(commodity.includes("openSpreadChart(spreadRow, '1d', 'continuous')"));
assert(commodity.includes('BUY ${esc(row.secondRole)} / SELL ${esc(row.firstRole)}'));
assert(commodity.includes("preset: 'ema_obv'") && commodity.includes('Three EMA'));
assert(commodity.includes('Dhan fixed brokerage') && commodity.includes('brokerageBreakevenPoints'));
assert(commodity.includes('notifySpread') && commodity.includes('target reached') && commodity.includes('stop reached'));
assert(commodity.includes('Trend 1D') && commodity.includes('Trade 4H'));
assert(commodity.includes('openSignalInChartWorkspace') && commodity.includes("timeframe === '4h' ? '4h' : timeframe === '1w' ? '1w' : '1d'"));
assert(!commodity.includes('physical commodity cash-and-carry profit'));
assert(css.includes('.commodity-watch') && css.includes('.commodity-detail') && css.includes('.commodity-table'));
assert(css.includes('.commodity-planner') && css.includes('.commodity-margin-result') && css.includes('.commodity-saved'));
assert(css.includes('.commodity-spread-research') && css.includes('.commodity-spread-svg') && css.includes('.commodity-spread-stats'));
assert(css.includes('.commodity-view-toggle') && css.includes('.commodity-lab-layout') && css.includes('.commodity-lab-detail'));
assert(css.includes('.commodity-spread-desk-layout') && css.includes('.commodity-spread-monitor'));
assert(css.includes('.commodity-spread-state-panel') && css.includes('.commodity-spread-brief') && css.includes('@keyframes commodity-spread-shimmer'));
assert(service.includes('buildCommodityFuturePairs') && service.includes("action === 'commodity_snapshot'"));
assert(service.includes('buildCommoditySpreadPairs') && service.includes("action === 'commodity_spread_scanner'"));
assert(service.includes("message.spreadType || 'all'"));
assert(service.includes('buildCommoditySpreadCandles') && service.includes("action === 'commodity_spread_chart'"));
assert(service.includes('mergeCommodityLiveSpread') && service.includes('commoditySpreadRefreshes'));
assert(service.includes("clipCommoditySpreadRowsForPair(pair, nearDaily.rows, farDaily.rows, '1d'"));
assert(service.includes('incompleteDailyWindow') && service.includes('repairCommoditySpreadGlitches'));
assert(chartSurfacePart.includes("preset: normalizePreset(state.preset || '') === 'ema_obv' ? 'decision'"));
assert(chartWorkspacePart.includes('force: options.forceData === true'));
assert(chartWorkspacePart.includes('chartPersistentCacheLoaded') && chartWorkspacePart.includes('DS_V17_CHART_CACHE_KEY'));
assert(chartEngine.includes("text: marker.type === 'expiry_fallback' ? 'Expiry roll' : 'OI roll'"));
assert(service.includes('buildCommoditySpreadClosePoints') && service.includes('buildCommoditySynchronizedSpreadCandles'));
assert(service.includes("action === 'commodity_spread_continuous_chart'"));
assert(service.includes("getCommodityCachedCandles(pair.secondInstrument, '1d'") && service.includes('isDegenerateCommoditySpread'));
assert(service.includes("daily: 'exact_active_contract_pair'"));
assert(service.includes("action === 'commodity_spread_history_backfill_start'"));
assert(service.includes("action === 'commodity_spread_history_backfill_status'"));
assert(service.includes("action === 'commodity_spread_history_backfill_cancel'"));
assert(service.includes("action === 'commodity_spread_expiry_catalog'"));
assert(service.includes('COMMODITY_CONTRACT_ARCHIVE_FILE') && service.includes('COMMODITY_SPREAD_HISTORY_FILE'));
assert(commodity.includes('BUY SPREAD') || commodity.includes("action.replace('_', ' ')"));
assert(commodity.includes('Continuous') && commodity.includes('Historical Expiries'));
assert(commodity.includes("marketData('commodity_spread_expiry_catalog'") && commodity.includes('Archived contract identities'));
assert(css.includes('.commodity-spread-expiry-catalog'));
assert(service.includes("action === 'commodity_spread_quotes'") && service.includes('getCommoditySpreadQuotes'));
assert(service.includes('COMMODITY_CANDLE_CACHE_FILE') && service.includes('getCommodityCachedCandles'));
assert(service.includes('canGapFetch') && service.includes('incremental: canGapFetch'));
assert(service.includes('DHAN_FUTURES_BROKERAGE_PER_ORDER') && service.includes('commoditySpreadSafeguards'));
assert(service.includes("action === 'commodity_margin_preview'") && service.includes("'/margincalculator'"));
assert(service.includes("action === 'commodity_spread_history'") && service.includes('buildCommoditySpreadHistory'));
assert(service.includes('dhanErrorMessage') && service.includes('isDhanNoHistoricalDataResponse'));
assert(service.includes('MCX_PRICE_MULTIPLIERS') && service.includes('expiryCode = Math.max'));
assert(service.includes("action === 'commodity_analysis'") && service.includes("continuousMode: 'front_month_expiry_code_0'"));
assert(service.includes('COMMODITY_ANALYSIS_CACHE_TTL_MS'));
assert(service.includes('timingSymbols') && commodity.includes("limit: 6, dailyDays: 1095, intradayDays: 90"));
assert(commodity.includes("safeTimeframe === '1d' ? 1095 : 520"));
assert(service.includes("'/margincalculator/multi'") && service.includes('scripList: legs.map') && service.includes('includeOrder: true'));
assert(service.includes("exchangeSegment !== 'MCX_COMM'") && service.includes("instrument !== 'FUTCOM'"));
assert(service.includes('Calendar spread observation compares near and next MCX futures.'));
assert(chartWorkspacePart.includes("...state.commoditySpread,\n resolution: timeframe") && chartWorkspacePart.includes("type: 'dhan_data',\n action: 'commodity_spread_continuous_chart'"));
assert(chartWorkspacePart.includes('signedPriceSeries: true'));
assert(chartIndicators.includes('options.allowSigned === true'));
assert(chartSurfacePart.includes("dataset?.signedPriceSeries === true"));
assert(chartEngine.includes("payload.dataset?.signedPriceSeries === true"));

console.log('Commodities Phase 3 smoke checks passed.');
